name: Send Telegram Alert

on:
  repository_dispatch:
    types: [new_task]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run bot
      run: python bot.py
